on: 
  push:
    branches:
      - feature/pipeline

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'app/package-lock.json'
    - run: npm i
    - run: npm run build
    
    - name: 🤳 Deploy website
      uses: XPH0816/webdav-deploy-action@v0.3
      with:
        url: webdisk.goldenharvestco.co.za
        username: ${{ secrets.WEBDAV_USERNAME }}
        password: ${{ secrets.WEBDAV_PASSWORD }}
        local: "./"
        remote: "public_html/"
